### ISSUE TITLE
ttf-parser v0.20 fails to compile on Rust 1.76

### ISSUE THREAD

**Issue by alice-i-cecile** [RazrFalcon/ttf-parser#141]
Found in taffy's CI here: https://github.com/DioxusLabs/taffy/actions/runs/7830890088/job/21366000249

```
error[E0309]: the parameter type `Ext` may not live long enough
  --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/read-fonts-0.15.3/src/tables/layout.rs:84:9
   |
84 | /         left.into_iter()
85 | |             .flatten()
86 | |             .chain(right.into_iter().flatten())
   | |_______________________________________________^ ...so that the type `Ext` will meet its required lifetime bounds
   |
help: consider adding an explicit lifetime bound...
   |
44 | impl<'a, T: FontRead<'a>, Ext: ExtensionLookup<'a, T> + 'a> Subtables<'a, T, Ext> {
   |                                                       ++++

error[E0309]: the parameter type `T` may not live long enough
  --> /home/runner/.cargo/registry/src/github.com-1ecc[62](https://github.com/DioxusLabs/taffy/actions/runs/7830890088/job/21366000249#step:5:63)99db9ec823/read-fonts-0.15.3/src/tables/layout.rs:84:9
   |
84 | /         left.into_iter()
85 | |             .flatten()
86 | |             .chain(right.into_iter().flatten())
   | |_______________________________________________^ ...so that the type `T` will meet its required lifetime bounds
   |
help: consider adding an explicit lifetime bound...
   |
44 | impl<'a, T: FontRead<'a> + 'a, Ext: ExtensionLookup<'a, T>> Subtables<'a, T, Ext> {
```

**Comment by alice-i-cecile** [comment]
Sorry, looks like it's actually in read-fonts. Misread the CI log.

**Comment by RazrFalcon** [comment]
No problem.
